baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'The LITzman outlet'
theme = 'nostyleplease' 

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true